version: '3'

services:
    mysql:
      image: 'mysql:latest'
      volumes:
        - ./:/mydata
      ports:
        - 9910:3306
      environment:
        - MYSQL_DATABASE=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_NATIVE_PASSWORD=root
        - MYSQL_RANDOM_ROOT_PASSWORD="no"
