version: '3'

services:
    mysql:
      image: 'mysql:latest'
      volumes:
        - ./:/mydata
      ports:
        - 9910:3306
      environment:
        - MYSQL_DATABASE=gorm
        - MYSQL_USER=gorm
        - MYSQL_PASSWORD=gorm
        - MYSQL_RANDOM_ROOT_PASSWORD="yes"
