version: '3'

services:
  mysql:
    image: 'mysql:latest'
    # ports:
    #   - 9910:3306
    environment:
      - MYSQL_DATABASE=world
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
